### ISSUE TITLE
580611025 to choose position "?"should be x/o for easy to understand

### ISSUE THREAD

**Issue by taeyeyta2539** [ISNE360260/DNWS#11]
# In the file  OXPlugin.cs

to choose position "?"should be x/o for easy to understand

![image](https://user-images.githubusercontent.com/16963005/36354028-ca9cf990-1500-11e8-8ab8-e79f13ffb4ed.png)

*********************************************************************************************************

_**I replace this code**_

                                    if (myPlayer == OXBoard.X_PLAYER)
                                    {
                                        sb.Append(String.Format("<a href=\"{0}&row={1}&col={2}\">X</a>", playLink, row, col));
                                    }
                                    else if (myPlayer == OXBoard.O_PLAYER)
                                    {
                                        sb.Append(String.Format("<a href=\"{0}&row={1}&col={2}\">O</a>", playLink, row, col));
                                    }

_**To this code**_

     sb.Append(String.Format("<a href=\"{0}&row={1}&col={2}\">?</a>", 

*********************************************************************************************************
_**Before**_

![image](https://user-images.githubusercontent.com/16963005/36354014-a530f7a6-1500-11e8-9aee-a58d035ba859.png)

**_After_**
![image](https://user-images.githubusercontent.com/16963005/36354005-8acac54a-1500-11e8-9b1c-5bb71d785275.png)

**Comment by pruet** [comment]
I feel like your fix will put ? on every cells, even then one that X/O already played, what do you think?
