### ISSUE TITLE
580611025 it should has background color

### ISSUE THREAD

**Issue by taeyeyta2539** [ISNE360260/DNWS#14]
In file OXPLUGIN.CS

add sb.Append("<body style=\"background-color: powderblue; ");

to

"public HTTPResponse GetResponse(HTTPRequest request)" Class

![image](https://user-images.githubusercontent.com/16963005/36303741-bf33f3fa-133f-11e8-9a15-b5d4cf52a6c6.png)

![image](https://user-images.githubusercontent.com/16963005/36303755-cede3900-133f-11e8-840a-9461d04a53fb.png)

**Comment by pruet** [comment]
white is good enough.
