### ISSUE TITLE
580611025 In create new players page , Button's name must be "Create"

### ISSUE THREAD

**Issue by taeyeyta2539** [ISNE360260/DNWS#15]
in file OXplugin.cs

in Condition "else if (parameters["action"] == "newplayer")"

Button's name must be "Create"

![image](https://user-images.githubusercontent.com/16963005/36304618-e1c78fbe-1342-11e8-8701-e73529948f88.png)

change

sb.Append("<input type=\"submit\" name=\"submit\" value=\"login\" /> <br />");

to

sb.Append("<input type=\"submit\" name=\"submit\" value=\"create\" /> <br />");

**Comment by PanuwatPhunsuk** [comment]
https://github.com/ISNE360260/DNWS/pull/117
