### ISSUE TITLE
580611028 show date time When access at OX home page

### ISSUE THREAD

**Issue by thanakorn028** [ISNE360260/DNWS#16]
I want to show date of time play game 
Code
![image](https://user-images.githubusercontent.com/21054966/36305146-f95d0404-1344-11e8-90a2-c96c72660f07.png)
I add 
sb.Append(DateTime.Now.ToString());

![image](https://user-images.githubusercontent.com/21054966/36305221-37c23228-1345-11e8-817a-cb77fdcc12f6.png)

**Comment by thanakorn028** [comment]
I will make couter time which is clock

**Comment by pruet** [comment]
What's the point of adding the clock?
