### ISSUE TITLE
580611048 In Create Page,we should have something to go back to the home page.

### ISSUE THREAD

**Issue by PanuwatPhunsuk** [ISNE360260/DNWS#17]
before
![image](https://user-images.githubusercontent.com/21043266/36308612-faddd740-1353-11e8-99ea-c67be5da4ef9.png)

after
![image](https://user-images.githubusercontent.com/21043266/36308571-d636285c-1353-11e8-8c2c-fa50d02eb53f.png)

![image](https://user-images.githubusercontent.com/21043266/36308589-e38d92b0-1353-11e8-9f32-c7a64cbacb94.png)

**Comment by PanuwatPhunsuk** [comment]
I forgot this,When I login to another user and click to create new user. if I don't want to create it.It must go back to ox page with old user. I will find the way later

**Comment by pruet** [comment]
Well, I'm not sure if this can be an enhance (but it won't be a bug), because the "go back" should not leave the application. What do you thing?.
