### ISSUE TITLE
580611003 When Player "O" win but game still wait !!

### ISSUE THREAD

**Issue by pond1003** [ISNE360260/DNWS#18]
> At first we let O win this game

![tmp06](https://user-images.githubusercontent.com/20939886/36309111-dac53cd0-1355-11e8-8509-a6a80158ebb8.PNG)

> Then we come back to account c 's home page but the result of game is still wait ??

![tmp07](https://user-images.githubusercontent.com/20939886/36309197-44675088-1356-11e8-8f3e-a0d4b535c8e0.PNG)

**Comment by pruet** [comment]
Ok, any idea to fix?
