### ISSUE TITLE
580611009 OX games should validate username from get method that are exist in player list or not?

### ISSUE THREAD

**Issue by nick30540** [ISNE360260/DNWS#21]
![validate_get_method](https://user-images.githubusercontent.com/36546300/36323679-47862fa4-1384-11e8-90f1-2e607ce7b414.png)

**Comment by nick30540** [comment]
Add code for check user are exist or not. If not exist tell them to login again

![screenshot_5](https://user-images.githubusercontent.com/36546300/36324361-d26fa2ba-1386-11e8-8f7c-7a5cd418abe2.png)

**Comment by pruet** [comment]
can we prevent multiple clients connect with the same user name?
