### ISSUE TITLE
580611009 If any player has log on should not have create new user or have button to create new user

### ISSUE THREAD

**Issue by nick30540** [ISNE360260/DNWS#22]
![screenshot_6](https://user-images.githubusercontent.com/36546300/36324812-3b0de830-1388-11e8-83a1-4b02670850c3.png)

Just remove this button when user is log on.

![screenshot_7](https://user-images.githubusercontent.com/36546300/36324956-b35a9c5c-1388-11e8-8fba-058a20b0481e.png)

**Comment by pruet** [comment]
Should we confirm whether the username is really the real username? (see #21)
