### ISSUE TITLE
580611065 when change url if we insert row and col without scope should not exception 

### ISSUE THREAD

**Issue by Apirom** [ISNE360260/DNWS#23]
before improvement

![maxthonsnap20180216114057](https://user-images.githubusercontent.com/20939849/36326819-4e4bc9e8-1311-11e8-9fcf-50ed2395fe88.png)
t 

after : 
![maxthonsnap20180213175329](https://user-images.githubusercontent.com/20939849/36326826-55e496e4-1311-11e8-8360-04b48ef09521.png)

code : 
![maxthonsnap20180216113658](https://user-images.githubusercontent.com/20939849/36326835-5da64f9e-1311-11e8-9483-14cb53181a06.png)

if we change url col=6 program will stopped after I insert try...catch. the program not stopped and it will show "error" in top of table

**Comment by pruet** [comment]
Good catch, but better error reporting, should we?
