### ISSUE TITLE
580611039 Catch Exception from input null or invalid game's number 

### ISSUE THREAD

**Issue by napornapon** [ISNE360260/DNWS#25]
Before:
![image](https://user-images.githubusercontent.com/21042208/36329941-625174d6-139a-11e8-920b-b0a805167d04.png)

Exception:
```
   else if (parameters["action"] == "playgame")
                    {
                        try
                        {
                           ...
                        }
                        catch (Exception e)
                        {
                            sb.Append("Invalid game#");
                        }
                    }
```
After :
![image](https://user-images.githubusercontent.com/21042208/36329836-ff28e29a-1399-11e8-8e55-213f0d60fe52.png)

**Comment by pruet** [comment]
Then, what can we do after this? go back in history?

**Comment by napornapon** [comment]
We can add redirect link to some where else maybe /ox page depends on what developer want
