### ISSUE TITLE
580611013 Class Player in OXPlugin should encrypt or hash password before store

### ISSUE THREAD

**Issue by commee67** [ISNE360260/DNWS#3]
When we create player, password of player doesn't encrypt or hash before store. It's easy to hack such as brute-force. So we must encrypt or hash before store with encapsulation.

Before
<img width="382" alt="screen shot 2561-02-14 at 11 31 52" src="https://user-images.githubusercontent.com/21051232/36187853-b018cbbe-117a-11e8-8338-cb8953aa1af1.png">

After Encapsulation Using .NET Properties
Ex.
```
    public class Player
    {
        ...
        protected String _password;
        public string Password
        {
            get { return _password; }
            set {
                if (password.Length >= 8){
                    _password = encrypt password or hashing password with your algorithm
                }
                else{
                    show "Passwords must be at least 8 characters"
                }    
           }
        }
     }
```

**Comment by pruet** [comment]
If we hash the password, then we might need to change Login method in OXPlugin class, any suggestion?

**Comment by chaloempong** [comment]
Sure, because it depends on your encrypt algorithm. Maybe, we should have at least 3 methods for processing encrypt and decrypt.
1. Computing hash 
2. Generating salt 
3. Checking password that match hash in Login method.
