### ISSUE TITLE
580611035 when create new player success shouldn't show password 

### ISSUE THREAD

**Issue by ISNE-1035** [ISNE360260/DNWS#30]
source file : OXPlugin.cs
line : 394

<img width="423" alt="screen shot 2561-02-17 at 15 19 09" src="https://user-images.githubusercontent.com/21054573/36339364-0a2f4452-13f6-11e8-8d4b-f5f064f794f1.png">

before
<img width="1136" alt="screen shot 2561-02-17 at 15 19 48" src="https://user-images.githubusercontent.com/21054573/36339365-0e653522-13f6-11e8-8471-db6015c46591.png">

after
<img width="1010" alt="screen shot 2561-02-17 at 15 22 57" src="https://user-images.githubusercontent.com/21054573/36339380-755c478e-13f6-11e8-8172-0a4aba827cd9.png">

<img width="288" alt="screen shot 2561-02-17 at 15 23 11" src="https://user-images.githubusercontent.com/21054573/36339381-7b260b32-13f6-11e8-96de-67ecfa81fd61.png">

**Comment by pruet** [comment]
Alirght

**Comment by pruet** [comment]
dup #2
