### ISSUE TITLE
580611042 Third Man player

### ISSUE THREAD

**Issue by papannakub** [ISNE360260/DNWS#34]
![28275447_1589274014454171_816473213_o](https://user-images.githubusercontent.com/15519289/36342912-cae9e918-1437-11e8-925d-533e77ca2e96.png)

Login with lulu 

and Have game with pruet

![28124789_1589274201120819_907132429_o](https://user-images.githubusercontent.com/15519289/36342921-ecd127c6-1437-11e8-90d4-227539a5cdce.png)

Then Log in With Xo

![28169664_1589274897787416_2077432146_o](https://user-images.githubusercontent.com/15519289/36342934-10619c2a-1438-11e8-9338-c849d0099dc4.png)

Click Join and then Error

![28169953_1589275131120726_874777542_o](https://user-images.githubusercontent.com/15519289/36342950-28a9b89e-1438-11e8-852a-b2ea342f98ff.png)

Change URL

http://localhost:8080/ox?action=joingame&game=0&username=xo

to 
http://localhost:8080/ox?action=playgame&game=0&username=xo

![28217449_1589275634454009_72594569_o](https://user-images.githubusercontent.com/15519289/36342962-5a6b799e-1438-11e8-810a-87597b11ddfc.png)

Now XO can play  In pruet's turn

![28207874_1589307227784183_998509971_o](https://user-images.githubusercontent.com/15519289/36342989-a775f200-1438-11e8-9b34-d8e932bcfdb1.png)

**Comment by pruet** [comment]
Good catch, any suggestion?
