### ISSUE TITLE
580611027 Improve code to check for unexpected side parameter

### ISSUE THREAD

**Issue by ThanapatSornsrivichai** [ISNE360260/DNWS#39]
-change if else so that it can check for unexpected side parameter.As shown below.
![q5](https://user-images.githubusercontent.com/36567807/36343130-b1c20288-143a-11e8-8234-1575012a1ffb.PNG)
![q8](https://user-images.githubusercontent.com/36567807/36343132-b7e4fc6a-143a-11e8-97b9-9d2df64d3794.PNG)

**Comment by pruet** [comment]
alright
