### ISSUE TITLE
580611003 to verify that game.Status not be null

### ISSUE THREAD

**Issue by pond1003** [ISNE360260/DNWS#48]
Before : 
![image](https://user-images.githubusercontent.com/20939886/36412245-f2055684-164b-11e8-92cb-c100be3d2680.png)

After : 
![image](https://user-images.githubusercontent.com/20939886/36412291-22f8b876-164c-11e8-9366-eb4c4cb39542.png)

For Avoid Program cash

**Comment by pruet** [comment]
Good find
