### ISSUE TITLE
580611044 counting should begin at 1 not 0

### ISSUE THREAD

**Issue by peech44** [ISNE360260/DNWS#5]
count start at 0 ??? nonoNo
![work1](https://user-images.githubusercontent.com/21054559/36298711-fe711336-132b-11e8-9150-a0d71d9732a4.png)
we must to change 
![work2](https://user-images.githubusercontent.com/21054559/36298724-1ab07460-132c-11e8-894f-e312e8151349.png)

at here
![work3](https://user-images.githubusercontent.com/21054559/36298729-1fd4b136-132c-11e8-9335-abd6556c236f.png)

**Comment by pruet** [comment]
Alright....   any idea to fix this?
