### ISSUE TITLE
580611033 when competitor already join game other one can't click join 

### ISSUE THREAD

**Issue by itsGno** [ISNE360260/DNWS#50]
![full](https://user-images.githubusercontent.com/20939659/36424633-9cde2ad4-1676-11e8-9660-d3a9445aef93.png)

![code](https://user-images.githubusercontent.com/20939659/36424730-f0ee18f0-1676-11e8-86b5-f84b00b31de1.png)

when competitor already join game other one can't click join

**Comment by pruet** [comment]
Good
