### ISSUE TITLE
580611065 duplicate string in O_WIN and CREATED_O

### ISSUE THREAD

**Issue by Apirom** [ISNE360260/DNWS#52]
Before :
![capture](https://user-images.githubusercontent.com/20939849/36427573-2c3232e4-1680-11e8-962c-43b3539a43a3.PNG)
![1](https://user-images.githubusercontent.com/20939849/36427574-2c657280-1680-11e8-8812-899af1e91106.PNG)

same string when O win 
![2](https://user-images.githubusercontent.com/20939849/36427589-37f7ca12-1680-11e8-9036-3334bd86d108.PNG)

still waiting list
![3](https://user-images.githubusercontent.com/20939849/36427605-4459332c-1680-11e8-9bc7-2fab899dcf30.PNG)

after chage code string O in O_WIN to be lowercase
![1](https://user-images.githubusercontent.com/20939849/36427663-6435e0aa-1680-11e8-85a2-0b42c99f57b5.PNG)

![2](https://user-images.githubusercontent.com/20939849/36427847-d2bfebb0-1680-11e8-8f74-035c879eea79.PNG)

**Comment by pruet** [comment]
Well, it might be a better fix than changing from O -> o
