### ISSUE TITLE
580611043 when refresh create new game page, new game will created

### ISSUE THREAD

**Issue by peerawit503** [ISNE360260/DNWS#54]
before refresh page
![image](https://user-images.githubusercontent.com/20939727/36428839-98c34e36-1683-11e8-80aa-d19508517776.png)

after refresh page

![image](https://user-images.githubusercontent.com/20939727/36428874-a7be610a-1683-11e8-811f-f16ca36ffef6.png)

**Comment by peerawit503** [comment]
i fix it by first create function to get index of _gameList for know how many game in _gameList

![image](https://user-images.githubusercontent.com/20939727/36540891-aedee662-180e-11e8-878c-e08f8558709f.png)

then when we go to chooseside action i send new parameter that know about how many game in now

![image](https://user-images.githubusercontent.com/20939727/36541009-1911cbe4-180f-11e8-8c50-1e6ac2217617.png)
 
and in chooseside action process i use GetGameIndex again

![image](https://user-images.githubusercontent.com/20939727/36541081-5a4d4610-180f-11e8-989d-19cc1b2ea6a5.png)
 
and check if index from parameter and current_index is equal 

![image](https://user-images.githubusercontent.com/20939727/36541192-b2511224-180f-11e8-9982-3034c3a67753.png)

So when we refresh page parameter index that we get from url is old index not equal to the current index it can't create new game

**Comment by pruet** [comment]
Goood
