### ISSUE TITLE
580611043 when we refresh Player added successfully page, game must not create user with same username and password

### ISSUE THREAD

**Issue by peerawit503** [ISNE360260/DNWS#56]
when refresh this page

![image](https://user-images.githubusercontent.com/20939727/36430048-cae57936-1686-11e8-989f-2ae71220a2d9.png)

game will have 2 similar username and password

![image](https://user-images.githubusercontent.com/20939727/36430124-f4d34c0a-1686-11e8-91ed-caae632617b6.png)

**Comment by peerawit503** [comment]
before fix

![image](https://user-images.githubusercontent.com/20939727/36432201-313c7784-168c-11e8-9605-9e55a3b735b6.png)

after fix

![image](https://user-images.githubusercontent.com/20939727/36432311-7a70ab14-168c-11e8-9cdf-d8ed57745f1f.png)


i add some code to check username already exist in list or not

**Comment by peerawit503** [comment]
when add duplicate user or refresh Player added succesfully page 

![image](https://user-images.githubusercontent.com/20939727/36432433-c7adcfc4-168c-11e8-9c51-d483ece11750.png)

**Comment by pruet** [comment]
duplicate with #54
