### ISSUE TITLE
580611003 In Log in page should  verify that user in userlist

### ISSUE THREAD

**Issue by pond1003** [ISNE360260/DNWS#6]
>When you in the home page of OX game there are content of "Welcome" + [username] 

![tmp02](https://user-images.githubusercontent.com/20939886/36297537-d8c4c7aa-1325-11e8-8d2f-54c56c5f811f.PNG)

>But the thing is if we try to login to user that dosen't in the playerlist ?

![tmp01](https://user-images.githubusercontent.com/20939886/36297374-198d6a36-1325-11e8-8c1d-01d3c28301e6.PNG)

>So form this code should we verify that this user is in playerlist ?
![tmp03](https://user-images.githubusercontent.com/20939886/36297874-9cdd4260-1327-11e8-88bf-e2d060814a60.PNG)

> Should we add some validate before it !

![tmp04](https://user-images.githubusercontent.com/20939886/36299312-f4a62f28-132e-11e8-8cc2-50fa887c77cd.PNG)

**Comment by pruet** [comment]
I don't see your complete code (the new one), but is it any better way to do this beside using userValid flag?
