### ISSUE TITLE
580611044 stat display have something wrong about "/"

### ISSUE THREAD

**Issue by peech44** [ISNE360260/DNWS#62]
it have '/' why we need that sysbol ????!!
![work14](https://user-images.githubusercontent.com/21054559/36470732-7f3a3e20-171e-11e8-99fa-e699135ad41c.png)

fix it 
![work15](https://user-images.githubusercontent.com/21054559/36470744-88fdff64-171e-11e8-901d-e7a7761b7511.png)

then it's ok
![work16](https://user-images.githubusercontent.com/21054559/36470750-9105b0c6-171e-11e8-90cf-950be6414be9.png)

**Comment by pruet** [comment]
we should show / for absolute path, but I agree that there is something wrong with / handle.
