### ISSUE TITLE
580611066 choose to play as X but save O

### ISSUE THREAD

**Issue by autapan1066** [ISNE360260/DNWS#7]
![1](https://user-images.githubusercontent.com/21040735/36299385-4bb3666e-132f-11e8-8570-8835ccd32bec.jpg)
![2](https://user-images.githubusercontent.com/21040735/36299390-4e09243a-132f-11e8-87c2-6f2d37f87eb0.jpg)

**Comment by autapan1066** [comment]
I'm looking for a solution.

**Comment by autapan1066** [comment]
Before
![Uploading 1.jpg…]()
After
![2](https://user-images.githubusercontent.com/21040735/36301107-4e77c104-1336-11e8-84a1-dca0700353a7.jpg)

Fixed, but the table is the same. I do not know what else is wrong.

**Comment by pruet** [comment]
alright, seem to be a simple fix....   can we move this code to logic side, not presentation side?
