### ISSUE TITLE
580611031 Server started unsuccessfully because of port its access permissions and endlessly try loop

### ISSUE THREAD

**Issue by hit19316** [ISNE360260/DNWS#74]
Some computer can't use port 8080. 

![screenshot 704](https://user-images.githubusercontent.com/17317996/36639432-2c747c54-1a3f-11e8-8ee6-3c3bab497c6b.png)

And it go endlessly loop.
I solved by try input another port by coding on **start()** in **program.cs**.

![image](https://user-images.githubusercontent.com/17317996/36639570-e14a8996-1a41-11e8-954a-3e3741afadea.png)

------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/17317996/36639472-0bcbfa6c-1a40-11e8-8995-c535ea6c148f.png)

## **result:**

Decide to use port 8000.

![screenshot 702](https://user-images.githubusercontent.com/17317996/36639494-81bb8c42-1a40-11e8-9086-361bc3dddd71.png)

If can't use try another port.

![screenshot 703](https://user-images.githubusercontent.com/17317996/36639499-851ea004-1a40-11e8-9724-20e15c3abbc9.png)

Stop loop by use variable attempt.

![image](https://user-images.githubusercontent.com/17317996/36639519-d98ecbf0-1a40-11e8-8e42-81b12e9892b0.png)

Said "it over attempt to start server" then break loop.

**Comment by pruet** [comment]
Good work
