### ISSUE TITLE
580611007 Add TodoController to Controllers for  User Controllers base on Models

### ISSUE THREAD

**Issue by earnearn07** [ISNE360260/DNWS#77]
![edit1](https://user-images.githubusercontent.com/21054544/36643664-800ff3f6-1a81-11e8-9482-3fb10d1b2ba5.jpg)

Add TodoController for handle browser requests.The controller handles route data and query values and passes these values to the model.  For example, http://localhost:8080/ox?username=earnearn_07  has route data of Users: earnearn_07 (the controller).

**Comment by pruet** [comment]
Where do you get that TodoController?
