### ISSUE TITLE
580611048 Should have link or button to go to the OX game in the index page

### ISSUE THREAD

**Issue by PanuwatPhunsuk** [ISNE360260/DNWS#8]
In the Index page we must write /ox to go to the OX game.If we create the button to go to the OX game in the index page.I Think , it will make it easy to other people to go to this game.
![image](https://user-images.githubusercontent.com/21043266/36301427-5dfd8e46-1337-11e8-90e2-48b26480f916.png)

**Comment by pruet** [comment]
Well, this is a web server, you can edit index.html to whatever you want, but it's not the "feature" of index.html to point to OX.
