### ISSUE TITLE
580611033 player can not create a new game when he does not have name on the Player's list 

### ISSUE THREAD

**Issue by itsGno** [ISNE360260/DNWS#85]
![maxthonsnap20180228212653](https://user-images.githubusercontent.com/20939659/36792871-6423c704-1cce-11e8-9a9d-e8dcb91521b2.png)

![ui](https://user-images.githubusercontent.com/20939659/36792927-8a797da4-1cce-11e8-9fce-16afc75e6876.png)

**Comment by pruet** [comment]
ok
