### ISSUE TITLE
580611033 Regular Expression for username validation

### ISSUE THREAD

**Issue by itsGno** [ISNE360260/DNWS#86]
![regular](https://user-images.githubusercontent.com/20939659/36795134-c9d33354-1cd4-11e8-823d-55b88dc09598.png)

![ui](https://user-images.githubusercontent.com/20939659/36795211-fe75600a-1cd4-11e8-99b1-d025f307c53b.png)

**Comment by pruet** [comment]
seem duplicate with #68
