### ISSUE TITLE
580611028 add music background

### ISSUE THREAD

**Issue by thanakorn028** [ISNE360260/DNWS#89]
I boring when to home it so quite.So I will add music you can open and close this
![28534530_1976743015686436_1047791185_n](https://user-images.githubusercontent.com/21054966/36799037-c009bba4-1cde-11e8-842e-a2fe89107b92.png)
![28579947_1976743545686383_557906937_o](https://user-images.githubusercontent.com/21054966/36799043-c4f60f28-1cde-11e8-9f01-ca58bff11d14.png)

**Comment by pruet** [comment]
No............
